version: '3.8'

services:
  mysql:
    image: mysql:8.1
    container_name: carrental-mysql
    restart: always
    environment:
      MYSQL_DATABASE: carrentaldb
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - carrental-network

  backend:
    build:
      context: C:\Users\vvhss\Desktop\CICD-insem\carrental-backend      # Path to Spring Boot project
      dockerfile: Dockerfile
    container_name: carrental-backend
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/carrentaldb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SERVER_PORT: 8081
    networks:
      - carrental-network

  frontend:
    build:
      context: C:\Users\vvhss\Desktop\CICD-insem\carrental-frontend     # Path to React frontend project
      dockerfile: Dockerfile
    container_name: carrental-frontend
    ports:
      - "8082:80"
    depends_on:
      - backend
    networks:
      - carrental-network

volumes:
  mysql-data:

networks:
  carrental-network:
    driver: bridge
